import type { ReactNode } from "react";

import { FallbackChip } from "@/components/agent/fallback-chip";
import { BADGE_BASE, ReportStatusBadge } from "@/components/status-badge";
import type { ArtifactOut } from "@/lib/types-agent";

interface ArtifactPanelProps {
  title: string;
  artifact: ArtifactOut | null;
  /** Shown when no artifact row exists yet. */
  emptyCopy: string;
  /** When set and the artifact has failed, a regenerate button is rendered. */
  onRegenerate?: () => void;
  regenerating?: boolean;
  /** Visual emphasis for the adjudication-summary panel. */
  highlighted?: boolean;
  /** Body rendered once the artifact is complete. */
  children?: ReactNode;
}

/**
 * Shared frame for the three dossier artifact panels: header with status badge,
 * deterministic-fallback chip, mandatory-review chip, provenance line, and the
 * pending/running/failed bodies. The complete body is supplied by the caller.
 */
export function ArtifactPanel({
  title,
  artifact,
  emptyCopy,
  onRegenerate,
  regenerating = false,
  highlighted = false,
  children,
}: ArtifactPanelProps) {
  const frame = highlighted
    ? "rounded-lg border border-violet-200 bg-white p-6 shadow-sm ring-1 ring-violet-100"
    : "rounded-lg border border-slate-200 bg-white p-6 shadow-sm";

  return (
    <section className={frame}>
      <div className="flex flex-wrap items-center gap-2">
        <h2 className="mr-auto text-sm font-semibold text-slate-900">{title}</h2>
        {artifact !== null ? (
          <>
            {artifact.requires_mandatory_review ? (
              <span className={`${BADGE_BASE} bg-red-50 text-red-700 ring-red-200`}>
                Mandatory review
              </span>
            ) : null}
            <FallbackChip reason={artifact.fallback_reason} />
            <ReportStatusBadge status={artifact.status} />
          </>
        ) : (
          <ReportStatusBadge status={null} />
        )}
      </div>

      {artifact === null ? (
        <p className="mt-3 text-sm text-slate-500">{emptyCopy}</p>
      ) : artifact.status === "pending" || artifact.status === "running" ? (
        <p className="mt-3 animate-pulse text-sm text-slate-500">Analysis in progress...</p>
      ) : artifact.status === "failed" ? (
        <div className="mt-3 rounded-md border border-red-200 bg-red-50 px-4 py-3">
          <p className="text-sm text-red-700">
            Automated analysis failed for this stage. You can regenerate it or proceed with a
            manual review.
          </p>
          {onRegenerate !== undefined ? (
            <button
              type="button"
              disabled={regenerating}
              onClick={onRegenerate}
              className="mt-2 rounded-md border border-red-300 bg-white px-3 py-1.5 text-sm font-medium text-red-700 transition-colors hover:bg-red-100 disabled:opacity-50"
            >
              {regenerating ? "Regenerating..." : "Regenerate analysis"}
            </button>
          ) : null}
        </div>
      ) : (
        <div className="mt-3">{children}</div>
      )}

      {artifact !== null && artifact.generated_by.length > 0 ? (
        <p className="mt-3 text-xs text-slate-400">
          Generated by {artifact.generated_by === "fallback_template" ? "deterministic template" : artifact.generated_by}
        </p>
      ) : null}
    </section>
  );
}
